apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wodo-payment-api
  namespace: wodo
#spec:
  #test:
    #enable: false
  #values:
    #ingress:
      #hosts:
        #- wodo-payment-api.staging